---
# common handlers

- name: update pam-auth
  command: "pam-auth-update --package"

- name: restart nslcd
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nslcd
    - nscd

- name: restart samba
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nmbd
    - smbd

- name: restart sshd
  service:
    name: ssh
    state: restarted

- name: stop mysql
  service:
    name: mysql
    state: stopped

- name: restart nginx
  service:
    name: nginx
    state: restarted

